---

#- hosts: 127.0.0.1
#  connection: local
#  roles:
#     - strongswan-ca

- hosts: cert-gen
  roles:
     - strongswan-packages
     - strongswan-certs

- hosts: vpn
  roles:
     - strongswan-packages
     - strongswan
#    - tinc

- hosts: removevpn
  roles:
    - tinc-remove
