---

- name: set hostname
  hostname: name={{ inventory_hostname }}
  become: true

- name: updating sudoers to prevert ansible synchronize error with sido tty
  lineinfile: >
       dest=/etc/sudoers
       line="# Defaults    requiretty"
       regexp="Defaults\s\s\s\srequiretty"
       create=yes
  become: true

- name: ensure /etc/strongswan/ipsec.d directory exists
  file:
    path: "/etc/strongswan/ipsec.d"
    state: directory
  become: true

- name: transfer the ca cert
  copy: src=strongswan_certs/cacerts dest=/etc/strongswan/ipsec.d
  become: true

#- name: sync the cert files on each host
#  synchronize: >
#    src=strongswan_certs/certs
#    dest=/etc/strongswan/ipsec.d
##  become: true

- name: copy the cert files on each host
  copy: >
   src=strongswan_certs/certs
   dest=/etc/strongswan/ipsec.d
  become: true

#- name: sync the keys files on each host
#  synchronize: >
#    src=strongswan_certs/private/{{ inventory_hostname }}-hostKey.pem
#    dest=/etc/strongswan/ipsec.d/private/
##  become: true

- name: copy the keys files on each host
  copy: >
   src=strongswan_certs/private/{{ inventory_hostname }}-hostKey.pem
   dest=/etc/strongswan/ipsec.d/private/{{ inventory_hostname }}-hostKey.pem
  become: true


- name: ensure /etc/strongswan/ directory exists
  file:
    path: "/etc/strongswan/"
    state: directory
  become: true

- name: create ipsec.secrets file (redhat)
  template: >
    src=ipsec.secrets.j2
    dest=/etc/strongswan/ipsec.secrets
    force=yes
  become: true

- name: enable strongswan service
  shell: systemctl enable strongswan
  become: true

- name: create ipsec.conf file (redhat)
  template: >
    src=ipsec.conf.j2
    dest=/etc/strongswan/ipsec.conf
    force=yes
  become: true
  notify:
    - start strongswan

