---

# coping files to server

- name: sync scripts
  synchronize: >
    src=roles/strongswan-certs/files/
    dest=~/strongswan_certs

# generating CA certificate

- name: ensure strongswan_certs directory exists
  file:
    path: "strongswan_certs"
    state: directory
  become: true

- name: register stat for strongswanCert.pem  file
  stat: path=strongswan_certs/cacerts/strongswanCert.pem
  register: ca_cert
  become: true

- name: generate ca certificate
  shell: ./ca_key.sh {{ swan_c }} {{ swan_o }} {{ inventory_hostname }} chdir=strongswan_certs
  when: ca_cert.stat.exists != true
  register: ca_cert_gen
  become: true

- name: show CA generation output to Ansible
  debug: msg="{{ ca_cert_gen.stdout_lines }}"
  when: ca_cert.stat.exists != true and {{ vpn_encryption }} == true
  become: true

# generating hosts certificates

- name: register host cert file stats
  stat: path=strongswan_certs/certs/{{ hostvars[item]['inventory_hostname'] }}-hostCert.pem
  register: hosts_certs_path
  with_items: "{{ groups['vpn'] }}"

- name: generate hosts certificates
  shell: ./host_key.sh {{ swan_c }} {{ swan_o }} {{ hostvars[item[1]]['inventory_hostname'] }} chdir=strongswan_certs
  register: hosts_certs_gen_output
  when: item[0].stat.exists != true
  become: true
  with_nested:
    - "{{ hosts_certs_path.results }}"
    - "{{ groups['vpn'] }}"

- name: show hosts generation output
  debug: msg="{{ item[2].stdout_lines }}"
  when: item[0].stat.exists != true and {{ vpn_encryption }} == true
  with_nested:
    - "{{ hosts_certs_path.results }}"
    - "{{ groups['vpn'] }}"
    - "{{ hosts_certs_gen_output.results  }}"

# fetching certificates

- name: ensure strongswan_certs directory exists
  local_action: >
    file path="strongswan_certs" state=directory

- name: sync scripts
  synchronize: >
    mode=pull
    src=~/strongswan_certs/
    dest=strongswan_certs
    recursive=yes
    set_remote_user=yes

#- name: pull certs via rsync scripts
#  local_action: >
#    shell rsync -a {{ ansible_ssh_user }}@{{ hostvars[inventory_hostname].ansible_host }}:~/strongswan_certs ./


###

